package in.jdsoft.dms.model;

// default package
// Generated Apr 26, 2016 11:56:10 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Document generated by hbm2java
 */
@Entity
@Table(name = "document", catalog = "jdsoftdms", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "document_name", "path" }),
		@UniqueConstraint(columnNames = "document_uuid") })
public class Document implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer documentId;
	private String documentName;
	private String documentUuid;
	private int lockStatus;
	private String lockInformation;
	private int editStatus;
	private String editInformation;
	private String path;
	private String documentAccess;

	public Document() {
	}

	public Document(String documentName, String documentUuid, int lockStatus, int editStatus) {
		this.documentName = documentName;
		this.documentUuid = documentUuid;
		this.lockStatus = lockStatus;
		this.editStatus = editStatus;
	}

	public Document(String documentName, String documentUuid, int lockStatus, String lockInformation, int editStatus,
			String editInformation, String path, String documentAccess) {
		this.documentName = documentName;
		this.documentUuid = documentUuid;
		this.lockStatus = lockStatus;
		this.lockInformation = lockInformation;
		this.editStatus = editStatus;
		this.editInformation = editInformation;
		this.path = path;
		this.documentAccess = documentAccess;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "document_id", unique = true, nullable = false)
	public Integer getDocumentId() {
		return this.documentId;
	}

	public void setDocumentId(Integer documentId) {
		this.documentId = documentId;
	}

	@Column(name = "document_name", nullable = false)
	public String getDocumentName() {
		return this.documentName;
	}

	public void setDocumentName(String documentName) {
		this.documentName = documentName;
	}

	@Column(name = "document_uuid", unique = true, nullable = false)
	public String getDocumentUuid() {
		return this.documentUuid;
	}

	public void setDocumentUuid(String documentUuid) {
		this.documentUuid = documentUuid;
	}

	@Column(name = "lock_status", nullable = false)
	public int getLockStatus() {
		return this.lockStatus;
	}

	public void setLockStatus(int lockStatus) {
		this.lockStatus = lockStatus;
	}

	@Column(name = "lock_information")
	public String getLockInformation() {
		return this.lockInformation;
	}

	public void setLockInformation(String lockInformation) {
		this.lockInformation = lockInformation;
	}

	@Column(name = "edit_status", nullable = false)
	public int getEditStatus() {
		return this.editStatus;
	}

	public void setEditStatus(int editStatus) {
		this.editStatus = editStatus;
	}

	@Column(name = "edit_information")
	public String getEditInformation() {
		return this.editInformation;
	}

	public void setEditInformation(String editInformation) {
		this.editInformation = editInformation;
	}

	@Column(name = "path")
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Column(name = "document_access")
	public String getDocumentAccess() {
		return this.documentAccess;
	}

	public void setDocumentAccess(String documentAccess) {
		this.documentAccess = documentAccess;
	}

}
