package in.jdsoft.dms.model;

// default package
// Generated Apr 26, 2016 11:56:10 AM by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Folder generated by hbm2java
 */
@Entity
@Table(name = "folder", catalog = "jdsoftdms", uniqueConstraints = { @UniqueConstraint(columnNames = "folder_code"),
		@UniqueConstraint(columnNames = { "folder_name", "parent_folder_id" }) })
public class Folder implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer folderId;
	private String folderName;
	private String folderCode;
	private Date createdDate;
	private Date modifiedDate;
	private String createdBy;
	private String modifiedBy;
	private Integer parentFolderId;

	public Folder() {
	}

	public Folder(String folderName, String folderCode, String createdBy, String modifiedBy) {
		this.folderName = folderName;
		this.folderCode = folderCode;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
	}

	public Folder(String folderName, String folderCode, Date createdDate, Date modifiedDate, String createdBy,
			String modifiedBy, Integer parentFolderId) {
		this.folderName = folderName;
		this.folderCode = folderCode;
		this.createdDate = createdDate;
		this.modifiedDate = modifiedDate;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.parentFolderId = parentFolderId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "folder_id", unique = true, nullable = false)
	public Integer getFolderId() {
		return this.folderId;
	}

	public void setFolderId(Integer folderId) {
		this.folderId = folderId;
	}

	@Column(name = "folder_name", nullable = false)
	public String getFolderName() {
		return this.folderName;
	}

	public void setFolderName(String folderName) {
		this.folderName = folderName;
	}

	@Column(name = "folder_code", unique = true, nullable = false)
	public String getFolderCode() {
		return this.folderCode;
	}

	public void setFolderCode(String folderCode) {
		this.folderCode = folderCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_date", length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "created_by", nullable = false)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "modified_by", nullable = false)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "parent_folder_id")
	public Integer getParentFolderId() {
		return this.parentFolderId;
	}

	public void setParentFolderId(Integer parentFolderId) {
		this.parentFolderId = parentFolderId;
	}

}
