package in.jdsoft.dms.model;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated Apr 26, 2016 11:56:10 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UsersAccess generated by hbm2java
 */
@Entity
@Table(name = "users_access", catalog = "jdsoftdms", uniqueConstraints = @UniqueConstraint(columnNames = "user_role_id"))
public class UsersAccess implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer usersAccessId;
	private Integer userRoleId;
	private String userControl;

	public UsersAccess() {
	}

	public UsersAccess(Integer userRoleId, String userControl) {
		this.userRoleId = userRoleId;
		this.userControl = userControl;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "users_access_id", unique = true, nullable = false)
	public Integer getUsersAccessId() {
		return this.usersAccessId;
	}

	public void setUsersAccessId(Integer usersAccessId) {
		this.usersAccessId = usersAccessId;
	}

	@Column(name = "user_role_id", unique = true)
	public Integer getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(Integer userRoleId) {
		this.userRoleId = userRoleId;
	}

	@Column(name = "user_control")
	public String getUserControl() {
		return this.userControl;
	}

	public void setUserControl(String userControl) {
		this.userControl = userControl;
	}

}
