package in.jdsoft.dms.model;

// default package
// Generated Apr 26, 2016 11:56:10 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UsersRole generated by hbm2java
 */
@Entity
@Table(name = "users_role", catalog = "jdsoftdms", uniqueConstraints = @UniqueConstraint(columnNames = "role_name"))
public class UsersRole implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer userRoleId;
	private String roleName;

	public UsersRole() {
	}

	public UsersRole(String roleName) {
		this.roleName = roleName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_role_id", unique = true, nullable = false)
	public Integer getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(Integer userRoleId) {
		this.userRoleId = userRoleId;
	}

	@Column(name = "role_name", unique = true, nullable = false)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

}
